DROP DATABASE IF EXISTS globalFP_db;
CREATE DATABASE globalFP_db;
USE globalFP_db;

CREATE TABLE footprint(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    country VARCHAR (100) NULL,
    UN_region VARCHAR (100) NULL,
    year INTEGER NULL,
    carbon DECIMAL (20,10) NULL,
    Percapita_GDP DECIMAL(10,3) NULL,
    populations INTEGER (50) NOT NULL,
);

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;
