DROP DATABASE IF EXISTS globalFP_db;
CREATE DATABASE globalFP_db;
USE globalFP_db;

CREATE TABLE footprints(
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    country VARCHAR (100) NOT NULL,
    UN_region VARCHAR (100) NOT NULL,
    year INTEGER NOT NULL,
    carbon VARCHAR(20) NOT NULL,
    Percapita_GDP VARCHAR(20) NOT NULL,
    populations INTEGER (50) NOT NULL
);

SELECT * FROM footprints;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;
